name: Cypress Tests

on:
  push:
    branches: [devops-frontend]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Wait for EC2 server to be ready
        run: npx wait-on http://43.203.36.43
        working-directory: ./frontend

      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=http://43.203.36.43
        working-directory: ./frontend
