name: Frontend CI/CD (Test)

on:
  push:
    branches: [devops]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Vue Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/vue-test-app ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/vue-test-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/vue-test-app
          docker stop vue-test || true
          docker rm vue-test || true
          docker run -d --name vue-test -p 80:80 ${{ secrets.DOCKER_USERNAME }}/vue-test-app
